os: linux
dist: focal

language: node_js
node_js: 12.18.3

addons:
  apt:
    packages:
      - libgconf-2.4 # Required by Cypress

cache:
  yarn: true
  directories:
    - ~/.cache # Cypress binaries and Firebase emulators
    - .next/cache # Next.js build

before_install:
  - openssl aes-256-cbc -K $encrypted_d8d0a41d2890_key -iv $encrypted_d8d0a41d2890_iv -in firebase/functions/.runtimeconfig.json.enc -out firebase/functions/.runtimeconfig.json -d

install:
  - yarn install --immutable --immutable-cache
  - cd firebase/functions
  - npm install

before_script:
  - npm run build
  - cd ../../
  - yarn start:firebase & yarn wait-on http-get://localhost:8080
  - yarn build

script:
  - yarn start:next & yarn wait-on http://localhost:3000
  - yarn start:cy

env:
  - NODE_ENV=test
