os: linux
dist: focal

language: node_js
node_js: 12.18.3

addons:
  apt:
    packages:
      - libgconf-2.4 # Required by Cypress

cache:
  directories:
    - $HOME/.cache/Cypress
    - $HOME/.cache/firebase/emulators
    - $HOME/.cache/yarn
    - .next/cache

before_install:
  - openssl aes-256-cbc -K $encrypted_d8d0a41d2890_key -iv $encrypted_d8d0a41d2890_iv -in firebase/functions/.runtimeconfig.json.enc -out firebase/functions/.runtimeconfig.json -d

install:
  - yarn install --immutable --immutable-cache
  - cd firebase/functions
  - npm install

before_script:
  - npm run build
  - cd ../../
  - yarn start:firebase &>/dev/null & yarn wait-on http-get://localhost:8080
  - yarn build

script:
  - yarn start:next &>/dev/null & yarn wait-on http://localhost:3000
  - yarn start:cy

after_script:
  - bash <(curl -s https://codecov.io/bash)

env:
  - NODE_ENV=test
