os: linux
dist: focal

language: node_js
node_js: 12.18.3

addons:
  apt:
    packages:
      - libgconf-2.4 # Required by Cypress

cache:
  yarn: true
  directories:
    - ~/.cache # Cypress binary
    - .next/cache # Next.js build

install:
  - yarn
  - cd firebase/functions
  - npm install

before_script:
  - npm run build
  - cd ../../
  - yarn start:firebase & yarn wait-on http-get://localhost:8080
  - yarn build:ci

script:
  - yarn start:next &>/dev/null & yarn wait-on http://localhost:3000
  - yarn start:cy

env:
  - NODE_ENV=test
