language: node_js

node_js:
  - 12.18.3

addons:
  apt:
    packages:
      # Required dependency for running Cypress tests.
      # @see {@link https://docs.cypress.io/guides/guides/continuous-integration.html#Example-travis-yml-config-file}
      - libgconf-2.4

cache:
  yarn: true
  directories:
    # Cache the Cypress binary.
    - ~/.cache

install:
  - yarn
  - cd firebase/functions
  - npm install

before_script:
  - npm run build
  - cd ../../
  - yarn build:ci

script:
  - yarn start:firebase &>/dev/null & yarn wait-on http://localhost:8080
  - yarn start:client &>/dev/null & yarn wait-on http://localhost:3000
  - yarn start:cy
