os: linux
dist: focal

language: node_js
node_js: 12.18.3

addons:
  apt:
    packages:
      - libgconf-2.4 # Required by Cypress

cache:
  directories:
    - $HOME/.cache/Cypress
    - $HOME/.cache/firebase/emulators
    - $HOME/.cache/yarn
    - .next/cache

env:
  - NODE_ENV=test

defaults: &defaults
  before_install:
    - openssl aes-256-cbc -K $encrypted_d8d0a41d2890_key -iv $encrypted_d8d0a41d2890_iv -in firebase/functions/.runtimeconfig.json.enc -out firebase/functions/.runtimeconfig.json -d

  install:
    - yarn install --immutable --immutable-cache
    - cd firebase/functions
    - npm install

  before_script:
    - npm run build
    - cd ../../
    - yarn start:firebase & yarn wait-on http-get://localhost:8080
    - yarn build

  script:
    - yarn start:next & yarn wait-on http://localhost:3000
    - yarn cypress run --record --parallel --headless --group $BROWSER -b $BROWSER

  after_script:
    - bash <(curl -s https://codecov.io/bash)

chrome: &chrome
  addons:
    chrome: stable
  env:
    - BROWSER=chrome

firefox: &firefox
  addons:
    firefox: latest
  env:
    - BROWSER=firefox

electron: &electron
  env:
    - BROWSER=electron

jobs:
  include:
    - name: Chrome 1
      <<: *chrome
      <<: *defaults
    - name: Chrome 2
      <<: *chrome
      <<: *defaults
    - name: Chrome 3
      <<: *chrome
      <<: *defaults
    - name: Firefox 1
      <<: *firefox
      <<: *defaults
    - name: Firefox 2
      <<: *firefox
      <<: *defaults
    - name: Firefox 3
      <<: *firefox
      <<: *defaults
    - name: Electron 1
      <<: *electron
      <<: *defaults
    - name: Electron 2
      <<: *electron
      <<: *defaults
    - name: Electron 3
      <<: *electron
      <<: *defaults
