nodeLinker: node-modules

packageExtensions:
  eslint-config-airbnb-typescript@8.0.x:
    peerDependencies:
      eslint: ^5.16.0 || ^6.8.0 || ^7.2.0
      eslint-plugin-import: ^2.21.2
      eslint-plugin-jsx-a11y: ^6.3.0
      eslint-plugin-react: ^7.20.0
      eslint-plugin-react-hooks: ^4 || ^3 || ^2.3.0 || ^1.7.0
  next-images@1.4.x:
    peerDependencies:
      webpack: ^4.0.0 || ^5.0.0
  next@9.5.x:
    peerDependencies:
      sass: ^1.3.0

yarnPath: .yarn/releases/yarn-2.3.3.cjs
