name: Integration Tests

on:
  push:
  pull_request:

env:
  NODE_ENV: test
  PERCY_PARALLEL_NONCE: github.token
  PERCY_PARALLEL_TOTAL: 9
  ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  FIREBASE_ADMIN_CLIENT_EMAIL: ${{ secrets.FIREBASE_ADMIN_CLIENT_EMAIL }}
  FIREBASE_ADMIN_KEY: ${{ secrets.FIREBASE_ADMIN_KEY }}
  INTERCOM_KEY: ${{ secrets.INTERCOM_KEY }}
  PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/firebase/emulators
            ~/.cache/Cypress
            ~/.cache/yarn
            .next/cache
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - run: yarn install --immutable --immutable-cache
      - run: yarn start:db & yarn wait-on http-get://localhost:8080
      - run: yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            .next
            public/sw.js
  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [electron, firefox, chrome]
        parallel: [1, 2, 3]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/firebase/emulators
            ~/.cache/Cypress
            ~/.cache/yarn
            .next/cache
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - run: yarn install --immutable --immutable-cache
      - run: yarn start:db & yarn wait-on http-get://localhost:8080
      - uses: actions/download-artifact@v2
        with:
          name: build
      - run: yarn start:next & yarn wait-on http://localhost:3000
      - run: yarn start:cy --record --parallel --headless --group ${{ matrix.browser }} -b ${{ matrix.browser }}
      - uses: codecov/codecov-action@v1
