name: Tests

# Only trigger on push because PR commit messages don't point anywhere useful.
# @see {@link https://github.com/cypress-io/github-action#record-test-results-on-cypress-dashboard}
on: [push]

jobs:
  test:
    name: Cypress integration tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Automatically load balance tests across machines using Cypress.
        # @see {@link https://github.com/cypress-io/github-action#parallel}
        containers: [1, 2, 3, 4, 5, 6]
    steps:
      - uses: actions/checkout@v2
      # Cache the Firebase Emulator JAR files, Node.js deps, and Next.js build.
      # @see {@link https://firebase.google.com/docs/emulator-suite/install_and_configure#running_containerized_emulator_suite_images}
      # @see {@link https://github.com/vercel/next.js/blob/master/errors/no-cache.md#github-actions}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/firebase/emulators
            **/node_modules
            ${{ github.workspace }}/.next/cache
          key: ${{ hashFiles('**/yarn.lock', '**/package-lock.json') }}
      # We don't have to use `actions/cache` b/c Yarn Berry already adds our
      # deps to a git-tracked `.yarn/cache` folder. This merely unpacks it.
      # @see {@link https://yarnpkg.com/features/zero-installs}
      - name: Install project dependencies
        run: yarn
      - name: Install Firebase dependencies
        run: npm install
        working-directory: firebase/functions
      - name: Build Firebase functions
        run: npm run build
        working-directory: firebase/functions
      # TODO: Use the `wait-on` package to wait until these endpoints are
      # responding before continuing the run.
      # @see {@link https://npmjs.com/package/wait-on}
      - name: Start Firebase emulators
        run: yarn start:firebase &>/dev/null &
      - name: Build service worker and Next.js client
        run: yarn build
      - name: Start Next.js client
        run: yarn start:client &>/dev/null &
      # This action runs our tests and handles the Cypress Dashboard integration
      # (e.g. by sending GitHub commit information, etc).
      # @see {@link https://github.com/cypress-io/github-action}
      # @see {@link https://github.com/cypress-io/github-action/pulls/195}
      - name: Run Cypress integration tests
        uses: tutorbookapp/github-action@master
        with:
          record: true
          install: false
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Report code coverage info (from `coverage/lcov.info`) to Coveralls.
      # @see {@link https://github.com/coverallsapp/github-action}
      - name: Report Coveralls code coverage
        uses: coverallsapp/github-action@master
        with:
          parallel: true
          flag-name: run-${{ matrix.containers }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
  coverage:
    name: Coveralls code coverage
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Report Coveralls code coverage
        uses: coverallsapp/github-action@master
        with:
          parallel-finished: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

env:
  NODE_ENV: test
  FIRESTORE_EMULATOR_HOST: localhost:8080
  ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
  FIREBASE_ADMIN_CLIENT_EMAIL: ${{ secrets.FIREBASE_ADMIN_CLIENT_EMAIL }}
  FIREBASE_ADMIN_KEY: ${{ secrets.FIREBASE_ADMIN_KEY }}
